{% set name = "cuda-nvcc-impl" %}
{% set version = "12.8.61" %}
{% set cuda_version = "12.8" %}
{% set cuda_version_next_major = (cuda_version.split(".")[0]|int + 1)|string + ".0a0" %}
{% set gcc_min_constraint = ">=6" %}
{% set gcc_constraint = ">=6,<15.0a0" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-ppc64le" %}  # [ppc64le]
{% set platform = "linux-sbsa" %}  # [aarch64 and arm_variant_type == "sbsa"]
{% set platform = "linux-aarch64" %}  # [aarch64 and arm_variant_type == "tegra"]
{% set platform = "windows-x86_64" %}  # [win]
{% set target_name = "x86_64-linux" %}  # [linux64]
{% set target_name = "ppc64le-linux" %}  # [ppc64le]
{% set target_name = "sbsa-linux" %}  # [aarch64 and arm_variant_type == "sbsa"]
{% set target_name = "aarch64-linux" %}  # [aarch64 and arm_variant_type == "tegra"]
{% set target_name = "x64" %}  # [win]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]
{% set exists = "which" %}  # [not win]
{% set exists = "where" %}  # [win]
{% set sha256 = "145f8779bd56bdfa214447e5cb1b3a206ec1b7398da460e257f2898fd8604c54" %}  # [linux64]
{% set sha256 = "03f998e7d6c820479b18397276ac9067f4f757b0f94daec64454fdda373eb272" %}  # [aarch64 and arm_variant_type == "sbsa"]
{% set sha256 = "a02498cc0a4d3571587ac249185f6bdf3095dbead75cc3c3b2f11443c67b0255" %}  # [aarch64 and arm_variant_type == "tegra"]
{% set sha256 = "d0158c4dd6565c0c9bca50d2e0bd5fd944d40333725a1c6875ef1840b719abfc" %}  # [win]

package:
  name: cuda-nvcc-impl-split
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_nvcc/{{ platform }}/cuda_nvcc-{{ platform }}-{{ version }}-archive.{{ extension }}
  sha256: {{ sha256 }}
  patches:
    - nvcc.profile.patch      # [linux]
    - nvcc.profile.patch.win  # [win]

build:
  number: 1
  binary_relocation: false
  skip: true  # [osx or ppc64le]

requirements:
  build:
    - {{ stdlib("c") }}
    - cf-nvidia-tools
    - patchelf

outputs:
  - name: cuda-nvcc-tools
    files:                                  # [linux]
      - bin/*                               # [linux]
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - {{ stdlib("c") }}
      host:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
        - cuda-version {{ cuda_version }}
        - {{ pin_subpackage("cuda-crt-tools", exact=True) }}
        - {{ pin_subpackage("cuda-nvvm-tools", exact=True) }}
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
        - {{ pin_subpackage("cuda-crt-tools", exact=True) }}
        - {{ pin_subpackage("cuda-nvvm-tools", exact=True) }}
      run_constrained:
        - gcc_impl_{{ target_platform }} {{ gcc_constraint }}  # [linux]
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
    test:
      requires:
        - patchelf                                                # [linux]
      files:
        - patchelf_exclude.txt                                    # [linux]
        - test-rpath-nvcc.sh                                      # [linux]
      commands:
        - test -f $PREFIX/bin/nvcc                                # [linux]
        - test -f $PREFIX/bin/ptxas                               # [linux]
        - bash test-rpath-nvcc.sh                                 # [linux]
    about:
      home: https://developer.nvidia.com/cuda-toolkit
      license_file: LICENSE
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: Architecture independent part of CUDA NVCC compiler.
      description: |
        Compiler for CUDA applications.
      doc_url: https://docs.nvidia.com/cuda/index.html

  - name: cuda-nvcc-dev_{{ target_platform }}
    build:
      noarch: generic
      missing_dso_whitelist:                     # [win]
        - "*/api-ms-win-core-winrt-*.dll"        # [win]
    run_exports:
      strong:
        - cuda-version >={{ cuda_version }},<{{ cuda_version_next_major }}
    files:
      # targets/{{ target_name }}/bin/nvcc is only a symlink
      - targets/{{ target_name }}/bin          # [linux]
      - targets/{{ target_name }}/include/*.h  # [linux]
      - targets/{{ target_name }}/lib         # [linux]
      - Library\bin\*.exe                     # [win]
      - Library\bin\nvcc.profile              # [win]
      - Library\include\fatbinary_section.h   # [win]
      - Library\include\nvPTXCompiler.h       # [win]
      - Library\lib\nvptxcompiler_static.lib  # [win]
    requirements:
      build:
        - {{ stdlib("c") }}
      host:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
        - cuda-version {{ cuda_version }}
        - {{ pin_subpackage("cuda-nvcc-tools", exact=True) }}
        - {{ pin_subpackage("cuda-crt-dev_" + target_platform, exact=True) }}
        - {{ pin_subpackage("cuda-nvvm-dev_" + target_platform, exact=True) }}
        - libgcc {{ gcc_min_constraint }}  # [linux]
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
        - {{ pin_subpackage("cuda-crt-dev_" + target_platform, exact=True) }}
        - {{ pin_subpackage("cuda-nvvm-dev_" + target_platform, exact=True) }}
        - libgcc {{ gcc_min_constraint }}  # [linux]
        - arm-variant * {{ arm_variant_type }}    # [aarch64]
      run_constrained:
        - gcc_impl_{{ target_platform }} {{ gcc_constraint }}  # [linux]
    test:
      commands:
        - test -L $PREFIX/targets/{{ target_name }}/bin/nvcc      # [linux]
        - test -f $PREFIX/targets/{{ target_name }}/lib/libnvptxcompiler_static.a     # [linux]
        - test -f $PREFIX/targets/{{ target_name }}/include/fatbinary_section.h       # [linux]
        - test -f $PREFIX/targets/{{ target_name }}/include/nvPTXCompiler.h           # [linux]
        - if not exist %LIBRARY_BIN%\nvcc.exe exit 1                  # [win]
        - if not exist %LIBRARY_BIN%\nvcc.profile exit 1              # [win]
        - if not exist %LIBRARY_LIB%\nvptxcompiler_static.lib exit 1  # [win]
        - if not exist %LIBRARY_INC%\nvPTXCompiler.h exit 1           # [win]
    about:
      home: https://developer.nvidia.com/cuda-toolkit
      license_file: LICENSE
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: Target architecture dependent parts of CUDA NVCC compiler.
      description: |
        Compiler for CUDA applications.
      doc_url: https://docs.nvidia.com/cuda/index.html

  - name: cuda-nvcc-impl
    build:
      # libnvvm.so gets corrupted by patchelf. No need to relocate as it is already relocatable
      binary_relocation: False
    run_exports:
      strong:
        - cuda-version >={{ cuda_version }},<{{ cuda_version_next_major }}
    files:                             # [linux]
      - lib/libnvptxcompiler_static.a  # [linux]
    requirements:
      host:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
        - cuda-version {{ cuda_version }}
        - cuda-cudart-dev
        - {{ pin_subpackage("cuda-nvvm-impl", exact=True) }}
      run:
        - {{ pin_subpackage("cuda-nvcc-tools", exact=True) }}
        - {{ pin_subpackage("cuda-nvcc-dev_" + target_platform, exact=True) }}
        - {{ pin_subpackage("cuda-nvvm-impl", exact=True) }}
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
        - cuda-cudart-dev
      run_constrained:
        - gcc_impl_{{ target_platform }} {{ gcc_constraint }}  # [linux]
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
        - vc >={{ VCVER }}                      # [win]
    test:
      requires:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - {{ stdlib("c") }}
        - gxx              # [linux]
        - gcc              # [linux]
        - vs{{ VSYEAR }}_win-64 =={{ CL_VERSION }}  # [win]
        - cmake
        - cuda-driver-dev  # [linux]
        - git              # [linux]
        - ninja
      files:
        - test.cu
        - CMakeLists.txt
        - run_nvcc_tests.sh   # [linux]
        - run_nvcc_tests.bat  # [win]
      commands:
        - test -L $PREFIX/lib/libnvptxcompiler_static.a  # [linux]
        - {{ exists }} nvcc
        - ./run_nvcc_tests.sh   # [linux]
        - .\run_nvcc_tests.bat  # [win]
    about:
      home: https://developer.nvidia.com/cuda-toolkit
      license_file: LICENSE
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: Compiler for CUDA applications.
      description: |
        Compiler for CUDA applications.
      doc_url: https://docs.nvidia.com/cuda/index.html

  - name: cuda-crt-tools
    files:
      - bin/crt          # [linux]
      - Library\bin\crt  # [win]
    requirements:
      host:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
        - cuda-version {{ cuda_version }}
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
      run_constrained:
        - arm-variant * {{ arm_variant_type }}    # [aarch64]
    test:
      commands:
        - test -d $PREFIX/bin/crt            # [linux]
        - test -f $PREFIX/bin/crt/link.stub  # [linux]
        - if not exist %LIBRARY_BIN%\crt\link.stub exit 1  # [win]
    about:
      home: https://developer.nvidia.com/cuda-toolkit
      license_file: LICENSE
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: CUDA internal tools.
      description: |
        CUDA internal tools.
      doc_url: https://docs.nvidia.com/cuda/index.html

  - name: cuda-crt-dev_{{ target_platform }}
    build:
      noarch: generic
    run_exports:
      strong:
        - cuda-version >={{ cuda_version }},<{{ cuda_version_next_major }}
    files:
      - targets/{{ target_name }}/include/crt  # [linux]
      - Library\include\crt                    # [win]
    requirements:
      host:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
        - cuda-version {{ cuda_version }}
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
        - arm-variant * {{ arm_variant_type }}    # [aarch64]
    test:
      commands:
        - test -f $PREFIX/targets/{{ target_name }}/include/crt/common_functions.h  # [linux]
        - if not exist %LIBRARY_INC%\crt\common_functions.h exit 1  # [win]
    about:
      home: https://developer.nvidia.com/cuda-toolkit
      license_file: LICENSE
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: CUDA internal headers.
      description: |
        CUDA internal headers.
      doc_url: https://docs.nvidia.com/cuda/index.html

  - name: cuda-nvvm-tools
    files:
      - nvvm/bin                # [linux]
      - nvvm/libdevice          # [linux]
      - Library\nvvm\bin        # [win]
      - Library\nvvm\libdevice  # [win]
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - {{ stdlib("c") }}
      host:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
        - cuda-version {{ cuda_version }}
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
      run_constrained:
        - arm-variant * {{ arm_variant_type }}    # [aarch64]
    test:
      requires:
        - patchelf                                                # [linux]
      files:
        - test-rpath-nvvm.sh                                      # [linux]
      commands:
        - test -d $PREFIX/nvvm                                    # [linux]
        - test -f $PREFIX/nvvm/bin/cicc                           # [linux]
        - bash test-rpath-nvvm.sh                                 # [linux]
        - if not exist %LIBRARY_PREFIX%\nvvm\bin\cicc.exe exit 1  # [win]
        - if not exist %LIBRARY_PREFIX%\nvvm\libdevice exit 1     # [win]
    about:
      home: https://developer.nvidia.com/cuda-toolkit
      license_file: LICENSE
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: Compiler for CUDA applications.
      description: |
        Compiler for CUDA applications.
      doc_url: https://docs.nvidia.com/cuda/index.html

  - name: cuda-nvvm-dev_{{ target_platform }}
    build:
      noarch: generic
    files:                              # [linux]
      - targets/{{ target_name }}/nvvm  # [linux]
    requirements:
      host:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
        - cuda-version {{ cuda_version }}
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
        - arm-variant * {{ arm_variant_type }}    # [aarch64]
    test:
      commands:
        - test -L $PREFIX/targets/{{ target_name }}/nvvm          # [linux]
    about:
      home: https://developer.nvidia.com/cuda-toolkit
      license_file: LICENSE
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: Compiler for CUDA applications.
      description: |
        Compiler for CUDA applications.
      doc_url: https://docs.nvidia.com/cuda/index.html

  - name: cuda-nvvm-impl
    build:
      # libnvvm.so gets corrupted by patchelf. No need to relocate as it is already relocatable.
      binary_relocation: False
    files:
      - nvvm/include          # [linux]
      - nvvm/lib64            # [linux]
      - Library\nvvm\include  # [win]
      - Library\nvvm\lib      # [win]
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - {{ stdlib("c") }}
      host:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
        - cuda-version {{ cuda_version }}
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
      run_constrained:
        - arm-variant * {{ arm_variant_type }}    # [aarch64]
    test:
      requires:
        - patchelf                                                # [linux]
      files:
        - test-rpath-nvvm.sh                                      # [linux]
      commands:
        - test -d $PREFIX/nvvm/include  # [linux]
        - test -d $PREFIX/nvvm/lib64    # [linux]
        - bash test-rpath-nvvm.sh       # [linux]
        - if not exist %LIBRARY_PREFIX%\nvvm\include exit 1  # [win]
        - if not exist %LIBRARY_PREFIX%\nvvm\lib exit 1      # [win]
    about:
      home: https://developer.nvidia.com/cuda-toolkit
      license_file: LICENSE
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: Compiler for CUDA applications.
      description: |
        Compiler for CUDA applications.
      doc_url: https://docs.nvidia.com/cuda/index.html

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: Compiler for CUDA applications.
  description: |
    Compiler for CUDA applications.
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  feedstock-name: cuda-nvcc-impl
  recipe-maintainers:
    - conda-forge/cuda
